config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
resources :animes
resources :bots
resources :comments
resources :contacts
resources :contents
resources :works

    root to: "users#index"
  end

  root 'pages#index'

  get 'bots/crawl', to: 'bots#crawl'
  get 'bots/scraping', to: 'bots#scraping'
  get 'bots/scrap', to: 'bots#scrap'
  get 'bots/insert_content', to: 'bots#insert_content'
  get 'bots/insert_bot', to: 'bots#insert_bot'

  resources :bots, only: [:show, :index]
  resources :works, only: [:create, :destroy, :show, :index, :new, :edit, :update] do
    resources :comments, only: [:create, :destroy]
  end
  
  
  resources :contents, only: [:create, :destroy, :show, :index, :new, :edit, :update] do
    resources :comments, only: [:create, :destroy]
  end
  

  devise_for :users
  get 'pages/index_smart_phone', to: 'pages#index_smart_phone'

  resources :animes, only: [:create, :destroy, :show]
  
  resources :contacts, only: [:new, :create]
  
  resources :tweets, only: [:new, :create] do
    collection do
      get 'post'
    end
  end

end

app/views/pages/_footer.html.erb
<!-- フッター -->
<footer class="cols footer">
<div class="cols-inner">
<div class="col">


</div>
<div class="col">

	<ul>
		<!-- 1.モーダル表示のためのボタン -->
		<li><a data-toggle="modal" data-target="#modal-example">免責事項</a></li>
		<li><%= link_to "お問い合わせ", new_contact_path %></li>
	</ul>
	<div class="copyright">
	<p>Copyright &copy; CLIP</p>
	</div>


</div>
</div>
</footer>



<!-- 2.モーダルの配置 -->
<div class="modal" id="modal-example" tabindex="-1">
    <div class="modal-dialog">

        <!-- 3.モーダルのコンテンツ -->
        <div class="modal-content">
            <!-- 4.モーダルのヘッダ -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="modal-label">免責事項</h4>
            </div>
            <!-- 5.モーダルのボディ -->
            <div class="modal-body">
				当サイトはYouTube及び、その他動画投稿サイトで閲覧できるアニメのURLをまとめているリンク集サイトです。
				運営者は、動画のアップロード、またはそれを推奨・援助する行為は一切行っておりません。
				動画・音声等すべての知的所有権は著作者・団体に帰属しております。内容に関する質問は有権者に、動画のアップロード等の質問・削除依頼に関しましては各動画共有サイトへ直接お問合わせ下さい。
				紹介記事には万全の注意を期しておりますが、リンクや情報の正確性、完全性を保証するものではありません。 万が一不適切な表現を掲載している箇所がございましたらお知らせいただければ削除などの対処をさせていただきます。
				広告のお問い合わせはメールフォームからお知らせ下さい。（リンク切れ報告には利用しないでください） 
				なお、当サイトの利用で生じた損害に対し、当サイト運営者は一切の責任を負うものではありません。
            </div>
            <!-- 6.モーダルのフッタ -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
            </div>
        </div>
    </div>
</div>

app/views/pages/_header.html.erb
<div class="id-header">
  

  <div class="id-inline"><%= link_to "キャンディィ", root_path %></div>
  <div class="id-inline form-inline">
    <%= search_form_for @q do |f| %>
      <%= f.search_field :main_title_cont, :placeholder => "作品名", class: :"form-control input-sm" %>
      <%= f.submit :class => "form-control input-sm"%>
    <% end %>
  </div>
  <div class="id-inline"><%= link_to "動画一覧", contents_path %></div>
</div>

app/views/pages/_left_side.html.erb
<div class="id-main-box">
  <div class="id-inline">
    <div class="we-index">
    <div class="id-tw">
      アニメ速報はこちらで!!
      <div class="id-tw-ic">
        <%= link_to image_tag('twitter.png', { :border => '0', :size => "70x70", :alt => 'キャンディィアイコン', :class => 'tw-ic'}), 'https://twitter.com/candii_anime', { :target => "_blank"}%>
      </div>
    </div>
    <div class="id-ti">
      <%= search_form_for @q do |f| %>
        <%= f.search_field :main_title_cont, :placeholder => "作品名", class: :"form-control input-sm" %>
        <%= f.submit :class => "form-control input-sm"%>
      <% end %>
    </div><br><br><br>
    
    <div class="id-pd">
      <div style="text-align: center; height: 70px;"><%= link_to "動画一覧", contents_path, { :class => "btn btn-info btn-lg" }%></div>
    </div>
    
    <div class="id-ti">放映中アニメ</div>
    <div class="id-pd">
      <% doc = Nokogiri.HTML(open("http://tvanimedouga.blog93.fc2.com/")) %>
      <% doc.css('#menu1Block > div:nth-child(4) > div.menu1BlockBody > div > div > ul > li > a').each do |element| %>
      
        <% ani = element.inner_html %>
        
        <% @content = Content.find_by(title: ani) %>

          <% if !@content.blank? %>
          <% if ani == @content.title %>
            <%= link_to "#{ani}",  @content %><br>
          <% end %>
          <% end %>
        
      <% end %>
    </div>

    </div>
  </div>

app/views/pages/_right_side.html.erb
  <div class="id-inline">
    <div class="ranking">
      <div class="id-ti">ランキング</div>
        <div class="id-pd">
          <% @i = 0%>
          <% @ranks.first(25).each do |rank| %>
           <%= rank.rank %>
           <%= link_to "#{rank.sub_title.truncate(17)}", rank %><br>
          <% end %>
        </div>
    </div>
    <div class="ranking">
      <div class="id-ti">他のサイトを見てみる</div>
        <div class="id-pd">
         <%= link_to "Youtubeアニメ無料動画", "http://tvanimedouga.blog93.fc2.com/" %><br>
         <%= link_to "アニポ無料アニメ動画まとめ", "http://anipo.jp/" %><br>
         <%= link_to "高画質アニメ動画情報", "http://kodoanime01.blog136.fc2.com/" %><br>
         <%= link_to "junkch", "http://junkch.com/" %><br>
         <%= link_to "Gyao", "http://gyao.yahoo.co.jp/ct/anime/" %><br>
         <%= link_to "特選★アニメ動画紹介所", "http://freeanimedougadesu.blog70.fc2.com/" %><br>
         <%= link_to "アニメ動画倉庫.com", "http://anime.dougasouko.com/" %><br>
         <%= link_to "無料動画一覧 | バンダイチャンネル｜好きなアニメを楽しもう！", "http://www.b-ch.com/ttl/frmv_list.php/" %><br>
         <%= link_to "無料動画アニメポスト", "http://animepost.blog.fc2.com/" %><br>
        </div>
      </div>
      <div class="ranking">
        <div class="id-ti">動画が見つからない時は？</div>
          <div class="id-pd">
           <%= link_to "MioMio", "http://www.miomio.tv/ent/japan/" , { :target => "_blank"} %><br>
           <%= link_to "Anitube", "http://www.anitube.se/" , { :target => "_blank"} %><br>
           <%= link_to "ひまわり動画", "http://himado.in/" , { :target => "_blank"} %><br>
           <%= link_to "Youtube", "https://www.youtube.com/" , { :target => "_blank"} %><br>
           <%= link_to "Dailymotion", "http://www.dailymotion.com/jp" , { :target => "_blank"} %><br>
           <%= link_to "B9", "http://up.b9dm.com/" , { :target => "_blank"} %><br>
           <%= link_to "FC2", "http://video.fc2.com/ja/" , { :target => "_blank"} %><br>
           <%= link_to "Himatube", "http://himatube.se/" , { :target => "_blank"} %><br>
           <%= link_to "GoGoAnime", "http://ww1.gogoanime.io/" , { :target => "_blank"} %><br>
           <%= link_to "AnimeNova", "http://www.animenova.org/" , { :target => "_blank"} %><br>
           <%= link_to "GoodAnime", "http://www.goodanime.co/" , { :target => "_blank"} %><br>
           <%= link_to "KissAnime ←オススメ", "http://kissanime.ru//" , { :target => "_blank"} %><br>
           <%= link_to "Myvi", "http://www.myvi.ru/" , { :target => "_blank"} %><br>
          </div>
        </div>
    </div>
  </div>

app/views/pages/index.html.erb
<div class="sub-her">
  <%= link_to image_tag('candii.jpg', { :border => '0', :size => "50x40", :alt => 'キャンディィアイコン', :class => 'tw-ic'}), root_path %>
  <div><%= link_to "キャンディィ|アニメ無料動画", root_path %></div><br>
  <span class="sub-her-dis">　　--アニメの無料動画をまとめたサイトです。--</span>
</div>
<%= render 'left_side' %>

  <div class="id-inline">
    <div class="timeline">
      <div class="id-ti">タイムライン</div>
      <div class="id-pd">
        <% @works.reverse.first(25).each do |work|%>
          <%= work.date.strftime("%-m月 %-d日") if !work.date.nil? %>
          <%= link_to "#{work.sub_title.truncate(20)}", work %><br>
        <% end %>
      </div>
    </div>
    <div class="timeline_under">
      <div class="id-pd">
          <% @works.first(5).each do |work| %>
          <div class="id-ti-bd">
            <%= link_to"#{work.sub_title.truncate(25)}", work %>
            <% if !work.blank? %>
              <iframe width="280" height="205" src="<%= work.youtube %>" frameborder="0" allowfullscreen></iframe>
            <% end %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
      
    <%= render 'right_side'%>