config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
resources :animes
resources :bots
resources :comments
resources :contacts
resources :contents
resources :works

    root to: "users#index"
  end

  root 'pages#index'

  get 'bots/crawl', to: 'bots#crawl'
  get 'bots/scraping', to: 'bots#scraping'
  get 'bots/scrap', to: 'bots#scrap'
  get 'bots/insert_content', to: 'bots#insert_content'
  get 'bots/insert_bot', to: 'bots#insert_bot'

  resources :bots, only: [:show, :index]
  resources :works, only: [:create, :destroy, :show, :index, :new, :edit, :update] do
    resources :comments, only: [:create, :destroy]
  end
  
  
  resources :contents, only: [:create, :destroy, :show, :index, :new, :edit, :update] do
    resources :comments, only: [:create, :destroy]
  end
  

  devise_for :users
  get 'pages/index_smart_phone', to: 'pages#index_smart_phone'

  resources :animes, only: [:create, :destroy, :show]
  
  resources :contacts, only: [:new, :create]
  
  resources :tweets, only: [:new, :create] do
    collection do
      get 'post'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>キャンディィ|無料アニメサイト</title>
  <meta name="viewport" content="width=devise-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'candii.jpg' %>
</head>
<body>
  <% if controller.controller_name != "contacts" %>
    <%= render 'pages/header' %>
  <% end %>

  <% if controller.controller_name == 'bots' %>
    <%= link_to "ホームへ", bots_path %>
  <% end %>
  
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% elsif alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

<%= yield %>

  <% if controller.controller_name != "contacts" %>
  <%= render 'pages/footer' %>
  <% end %>
</body>
</html>